import { Search, SlidersHorizontal, X, ArrowDownWideNarrow } from 'lucide-react';
import { PRIORITY_LABELS, STATUS_LABELS } from '../utils/tickets.js';

export default function TicketToolbar({ query, search, setSearch, change, reset }) {
  return <div className="toolbar"><div className="toolbar-main">
    <div className="search-field"><Search size={18} /><label className="sr-only" htmlFor="search">Search tickets</label><input id="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by title or customer email…" autoComplete="off" />{search && <button className="icon-button" aria-label="Clear search" onClick={() => setSearch('')}><X size={15} /></button>}</div>
    <div className="filter-controls"><div className="select-field"><SlidersHorizontal size={15} /><label className="sr-only" htmlFor="status">Filter by status</label><select id="status" value={query.status || ''} onChange={(event) => change('status', event.target.value)}><option value="">All statuses</option>{Object.entries(STATUS_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>
    <div className="select-field"><label className="sr-only" htmlFor="priority">Filter by priority</label><select id="priority" value={query.priority || ''} onChange={(event) => change('priority', event.target.value)}><option value="">All priorities</option>{Object.entries(PRIORITY_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>
    <div className="select-field"><ArrowDownWideNarrow size={15} /><label className="sr-only" htmlFor="sort">Sort by creation date</label><select id="sort" value={query.sort || 'newest'} onChange={(event) => change('sort', event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></div></div>
  </div>{(query.status || query.priority || search) && <div className="active-filters"><span>Filtered by</span>{query.status && <span className="filter-chip">{STATUS_LABELS[query.status]}<button aria-label="Remove status filter" onClick={() => change('status', '')}><X size={12} /></button></span>}{query.priority && <span className="filter-chip">{PRIORITY_LABELS[query.priority]} priority<button aria-label="Remove priority filter" onClick={() => change('priority', '')}><X size={12} /></button></span>}{search && <span className="filter-chip search-chip">“{search}”</span>}<button className="text-button" onClick={reset}>Clear all</button></div>}</div>;
}
